node {
    stage("Build & test"){
        def mvnHome = tool 'M3'
        git 'https://github.com/gortazar/2.2.Pruebas-de-servicios-de-Internet.git'
        sh 'pwd'
        sh "ls ; cd ./2.2.Pruebas-de-servicios-de-Internet/tema1/spring-test-ejem1 ; '${mvnHome}/bin/mvn' clean package"
    }
    stage("Post") {
        archive './2.2.Pruebas-de-servicios-de-Internet/tema1/spring-test-ejem1/target/*.jar'
        junit './2.2.Pruebas-de-servicios-de-Internet/tema1/spring-test-ejem1/target/surefire-reports/*.xml'
    }
}